[package]
name = "pydeps"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.95"
walkdir = "2"
ctrlc = "3.4.2"

